//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SboxAnalyzers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MethodArgumentsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MethodArgumentsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SboxAnalyzers.Resources.MethodArgumentsResources", typeof(MethodArgumentsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events can define the amount and types of parameters that are sent to listeners. If this is not defined then it can become difficult to see what is meant to be passed and received..
        /// </summary>
        internal static string ListenerMethodArgumentsUndefinedDescription {
            get {
                return ResourceManager.GetString("ListenerMethodArgumentsUndefinedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible parameter mismatch, no MethodArgumentsAttribute is defined for this event.
        /// </summary>
        internal static string ListenerMethodArgumentsUndefinedMessageFormat {
            get {
                return ResourceManager.GetString("ListenerMethodArgumentsUndefinedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible event listener parameter mismatch.
        /// </summary>
        internal static string ListenerMethodArgumentsUndefinedTitle {
            get {
                return ResourceManager.GetString("ListenerMethodArgumentsUndefinedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events can define the amount of parameters that are sent to listeners..
        /// </summary>
        internal static string ListenerParameterCountMismatchDescription {
            get {
                return ResourceManager.GetString("ListenerParameterCountMismatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event listener must have {0} parameters.
        /// </summary>
        internal static string ListenerParameterCountMismatchMessageFormat {
            get {
                return ResourceManager.GetString("ListenerParameterCountMismatchMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event listener has an incorrect parameter count.
        /// </summary>
        internal static string ListenerParameterCountMismatchTitle {
            get {
                return ResourceManager.GetString("ListenerParameterCountMismatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events can define the types of parameters that are sent to listeners..
        /// </summary>
        internal static string ListenerParameterTypeMismatchDescription {
            get {
                return ResourceManager.GetString("ListenerParameterTypeMismatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parameter must be &apos;{0}&apos;.
        /// </summary>
        internal static string ListenerParameterTypeMismatchMessageFormat {
            get {
                return ResourceManager.GetString("ListenerParameterTypeMismatchMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event listener has an incorrect parameter type.
        /// </summary>
        internal static string ListenerParameterTypeMismatchTitle {
            get {
                return ResourceManager.GetString("ListenerParameterTypeMismatchTitle", resourceCulture);
            }
        }
    }
}
