//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SboxAnalyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NetPropertyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetPropertyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SboxAnalyzers.NetPropertyResources", typeof(NetPropertyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networked properties must be implemented as an auto property for them to function. Init setters do not count..
        /// </summary>
        internal static string AutoPropertyDescription {
            get {
                return ResourceManager.GetString("AutoPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networked properties must be implemented as an auto property { get; set; }.
        /// </summary>
        internal static string AutoPropertyMessageFormat {
            get {
                return ResourceManager.GetString("AutoPropertyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networked properties must be auto-implemented { get; set; }.
        /// </summary>
        internal static string AutoPropertyTitle {
            get {
                return ResourceManager.GetString("AutoPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change callback method must exist on the type as the name is defined or defaulted to. If default, it will look for &quot;On[PropertyName]Changed&quot;..
        /// </summary>
        internal static string ChangeMissingDescription {
            get {
                return ResourceManager.GetString("ChangeMissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change callback method &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string ChangeMissingMessageFormat {
            get {
                return ResourceManager.GetString("ChangeMissingMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change callback method is missing.
        /// </summary>
        internal static string ChangeMissingTitle {
            get {
                return ResourceManager.GetString("ChangeMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change callback must have two parameters. The first containing the old value; the second containing the new value..
        /// </summary>
        internal static string ChangeParameterCountDescription {
            get {
                return ResourceManager.GetString("ChangeParameterCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change callback needs two parameters, not {0}.
        /// </summary>
        internal static string ChangeParameterCountMessageFormat {
            get {
                return ResourceManager.GetString("ChangeParameterCountMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change callback parameter count mismatch.
        /// </summary>
        internal static string ChangeParameterCountTitle {
            get {
                return ResourceManager.GetString("ChangeParameterCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change callback method must have the parameter types be the same as the properties type..
        /// </summary>
        internal static string ChangeParameterTypeDescription {
            get {
                return ResourceManager.GetString("ChangeParameterTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change callback parameter type must be &apos;{0}&apos;.
        /// </summary>
        internal static string ChangeParameterTypeMessageFormat {
            get {
                return ResourceManager.GetString("ChangeParameterTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change callback parameter type mismatch.
        /// </summary>
        internal static string ChangeParameterTypeTitle {
            get {
                return ResourceManager.GetString("ChangeParameterTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local attribute is currently not implemented. See issue #2169 for updates..
        /// </summary>
        internal static string LocalDescription {
            get {
                return ResourceManager.GetString("LocalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local attribute is not implemented.
        /// </summary>
        internal static string LocalMessageFormat {
            get {
                return ResourceManager.GetString("LocalMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local attribute is not implemented.
        /// </summary>
        internal static string LocalTitle {
            get {
                return ResourceManager.GetString("LocalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all types can be networked in S&amp;box. See https://wiki.facepunch.com/sbox/Networked_Types for currently networkable types..
        /// </summary>
        internal static string NetworkableDescription {
            get {
                return ResourceManager.GetString("NetworkableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not networkable.
        /// </summary>
        internal static string NetworkableMessageFormat {
            get {
                return ResourceManager.GetString("NetworkableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type is not networkable.
        /// </summary>
        internal static string NetworkableTitle {
            get {
                return ResourceManager.GetString("NetworkableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static properties cannot be networked..
        /// </summary>
        internal static string StaticDescription {
            get {
                return ResourceManager.GetString("StaticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static properties cannot be networked.
        /// </summary>
        internal static string StaticMessageFormat {
            get {
                return ResourceManager.GetString("StaticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static properties cannot be networked.
        /// </summary>
        internal static string StaticTitle {
            get {
                return ResourceManager.GetString("StaticTitle", resourceCulture);
            }
        }
    }
}
